# Stubs for json.decoder (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from _json import scanstring as c_scanstring

class JSONDecoder:
    encoding = ... # type: Any
    object_hook = ... # type: Any
    object_pairs_hook = ... # type: Any
    parse_float = ... # type: Any
    parse_int = ... # type: Any
    parse_constant = ... # type: Any
    strict = ... # type: Any
    parse_object = ... # type: Any
    parse_array = ... # type: Any
    parse_string = ... # type: Any
    scan_once = ... # type: Any
    def __init__(self, encoding=None, object_hook=None, parse_float=None, parse_int=None, parse_constant=None, strict=True, object_pairs_hook=None): ...
    def decode(self, s, _w=...): ...
    def raw_decode(self, s, idx=0): ...
