# Stubs for dockerfile_parse.constants (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

PY2 = ... # type: Any
DOCKERFILE_FILENAME = ... # type: Any
