# Stubs for docker.auth (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .auth import INDEX_NAME as INDEX_NAME, INDEX_URL as INDEX_URL, encode_header as encode_header, load_config as load_config, resolve_authconfig as resolve_authconfig, resolve_repository_name as resolve_repository_name
