# Stubs for docker.api.build (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

log = ... # type: Any

class BuildApiMixin:
    def build(self, path=None, tag=None, quiet=False, fileobj=None, nocache=False, rm=False, stream=False, timeout=None, custom_context=False, encoding=None, pull=False, forcerm=False, dockerfile=None, container_limits=None, decode=False, buildargs=None, gzip=False): ...
