# Stubs for docker (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
from .version import version_info as version_info
from .client import Client as Client, from_env as from_env

__title__ = ... # type: Any
