# Stubs for docker.client (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import requests
from .api import BuildApiMixin, ContainerApiMixin, DaemonApiMixin, ExecApiMixin, ImageApiMixin, VolumeApiMixin, NetworkApiMixin
from .auth import auth as auth
from .unixconn import unixconn as unixconn
from .ssladapter import ssladapter as ssladapter
from .utils import utils as utils, check_resource as check_resource, update_headers as update_headers, kwargs_from_env as kwargs_from_env
from .tls import TLSConfig as TLSConfig

def from_env(**kwargs): ...

class Client(requests.Session, BuildApiMixin, ContainerApiMixin, DaemonApiMixin, ExecApiMixin, ImageApiMixin, VolumeApiMixin, NetworkApiMixin):
    base_url = ... # type: Any
    timeout = ... # type: Any
    def __init__(self, base_url=None, version=None, timeout=..., tls=False): ...
    @classmethod
    def from_env(cls, **kwargs): ...
    def get_adapter(self, url): ...
    @property
    def api_version(self): ...
