# Stubs for docker.constants (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

DEFAULT_DOCKER_API_VERSION = ... # type: Any
DEFAULT_TIMEOUT_SECONDS = ... # type: Any
STREAM_HEADER_SIZE_BYTES = ... # type: Any
CONTAINER_LIMITS_KEYS = ... # type: Any
INSECURE_REGISTRY_DEPRECATION_WARNING = ... # type: Any
