# Stubs for docker.ssladapter.ssl_match_hostname (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

CertificateError = ... # type: Any

def match_hostname(cert, hostname): ...
