# Stubs for docker.unixconn.unixconn (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any
import httplib
import urllib3.connectionpool
import requests.adapters

RecentlyUsedContainer = ... # type: Any

class UnixHTTPConnection(httplib.HTTPConnection):
    base_url = ... # type: Any
    unix_socket = ... # type: Any
    timeout = ... # type: Any
    def __init__(self, base_url, unix_socket, timeout=60): ...
    sock = ... # type: Any
    def connect(self): ...

class UnixHTTPConnectionPool(urllib3.connectionpool.HTTPConnectionPool):
    base_url = ... # type: Any
    socket_path = ... # type: Any
    timeout = ... # type: Any
    def __init__(self, base_url, socket_path, timeout=60): ...

class UnixAdapter(requests.adapters.HTTPAdapter):
    socket_path = ... # type: Any
    timeout = ... # type: Any
    pools = ... # type: Any
    def __init__(self, socket_url, timeout=60): ...
    def get_connection(self, url, proxies=None): ...
    def request_url(self, request, proxies): ...
    def close(self): ...
