# Stubs for docker.utils (Python 2)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .utils import compare_version as compare_version, convert_port_bindings as convert_port_bindings, convert_volume_binds as convert_volume_binds, mkbuildcontext as mkbuildcontext, tar as tar, exclude_paths as exclude_paths, parse_repository_tag as parse_repository_tag, parse_host as parse_host, kwargs_from_env as kwargs_from_env, convert_filters as convert_filters, datetime_to_timestamp as datetime_to_timestamp, create_host_config as create_host_config, create_container_config as create_container_config, parse_bytes as parse_bytes, ping_registry as ping_registry, parse_env_file as parse_env_file, version_lt as version_lt, version_gte as version_gte, decode_json_header as decode_json_header, split_command as split_command, create_ipam_config as create_ipam_config, create_ipam_pool as create_ipam_pool, parse_devices as parse_devices, normalize_links as normalize_links
from .types import Ulimit as Ulimit, LogConfig as LogConfig
from .decorators import check_resource as check_resource, minimum_version as minimum_version, update_headers as update_headers
